name: "Active Scan"
description: "Run Noname Active CLI scan against the current repository"
author: "Noname Security"
inputs:
  active-registry-url:
    description: "Active Docker registry URL"
    required: true
  active-registry-user:
    description: "Active Docker registry username"
    required: true
  active-registry-password:
    description: "Active Docker registry password / JSON key (use a secret)"
    required: true
  active-api-url:
    description: "Active API URL (e.g. https://mimic-clean-14323.nonamesec.com/active)"
    required: true
  active-api-token:
    description: "Active API token (JWT) – pass via secret"
    required: true
  active-backend-uri:
    description: "Active backend URI"
    required: true
  test-group-id:
    description: "Test group ID"
    required: true
  environment-name:
    description: "Environment / branch name"
    required: false
    default: "${{ github.ref_name }}"
  active-config-file-path:
    description: "Path inside container to config file (mounted from ./akamai)"
    required: false
    default: "/akamai/environment.json"
  verbose:
    description: "Enable verbose output"
    required: false
    default: "false"
  analyze:
    description: "Enable analyze mode"
    required: false
    default: "false"
  severity-threshold:
    description: "Severity threshold (e.g. HIGH, MEDIUM)"
    required: false
    default: ""
  issue-threshold:
    description: "Issue threshold (string)"
    required: false
    default: ""
  category-threshold:
    description: "Category threshold (string)"
    required: false
    default: ""
  concurrency:
    description: "Concurrency level (number)"
    required: false
    default: ""
  timeout:
    description: "Timeout in seconds (number)"
    required: false
    default: ""
  proxy:
    description: "HTTP proxy URL"
    required: false
    default: ""
  backend-proxy:
    description: "Backend HTTP proxy URL"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Log versions / debug
      shell: bash
      run: |
        echo "Running Active scan..."
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Branch / ref: $GITHUB_REF_NAME"

    - name: Docker login to Active registry
      shell: bash
      run: |
        set -euo pipefail
        docker login "${{ inputs.active-registry-url }}" \
          -u "${{ inputs.active-registry-user }}" \
          -p "${{ inputs.active-registry-password }}"

    - name: Run Active CLI scan
      shell: bash
      run: |
        set -euo pipefail

        # Fetch CLI image version from Active API
        VERSION=$(curl -ks "${{ inputs.active-api-url }}/backend/version")
        echo "Using active-cli image tag: $VERSION"

        docker run \
          --network=host \
          -e ACTIVE_CONFIG_FILE_PATH="${{ inputs.active-config-file-path }}" \
          -e ACTIVE_BACKEND_URI="${{ inputs.active-backend-uri }}" \
          $(if [[ -n "${{ inputs.backend-proxy }}" ]]; then \
             if [[ "${{ inputs.backend-proxy }}" == http:* ]]; then \
               echo "-e ACTIVE_REMOTE_WORKER_HTTP_PROXY='${{ inputs.backend-proxy }}'"; \
             else \
               echo "-e ACTIVE_REMOTE_WORKER_HTTPS_PROXY='${{ inputs.backend-proxy }}'"; \
             fi; \
           fi) \
          -v "$GITHUB_WORKSPACE/akamai:/akamai" \
          "${{ inputs.active-registry-url }}/active-cli:${VERSION}" \
          scan \
          --api-url="${{ inputs.active-api-url }}" \
          --api-token="${{ inputs.active-api-token }}" \
          --test-group-id="${{ inputs.test-group-id }}" \
          --branch-name="${{ inputs.environment-name }}" \
          $([[ "${{ inputs.verbose }}" == "true" ]] && echo "--verbose") \
          $([[ "${{ inputs.analyze }}" == "true" ]] && echo "--analyze") \
          $([[ -n "${{ inputs.severity-threshold }}" ]] && echo "--severity-threshold='${{ inputs.severity-threshold }}'") \
          $([[ -n "${{ inputs.issue-threshold }}" ]] && echo "--issue-threshold='${{ inputs.issue-threshold }}'") \
          $([[ -n "${{ inputs.category-threshold }}" ]] && echo "--category-threshold='${{ inputs.category-threshold }}'") \
          $([[ -n "${{ inputs.concurrency }}" ]] && echo "--concurrency='${{ inputs.concurrency }}'") \
          $([[ -n "${{ inputs.timeout }}" ]] && echo "--timeout='${{ inputs.timeout }}'") \
          $([[ -n "${{ inputs.proxy }}" ]] && echo "--proxy='${{ inputs.proxy }}'")
