name: "Active Scan"
description: "Run Noname Active CLI scan against the current repository"
author: "Noname Security"
inputs:
  ACTIVE_REGISTRY_URL:
    description: "Active Docker registry URL"
    required: true
  ACTIVE_REGISTRY_USER:
    description: "Active Docker registry username"
    required: true
  ACTIVE_REGISTRY_PASSWORD:
    description: "Active Docker registry password / JSON key (use a secret)"
    required: true
  ACTIVE_API_URL:
    description: "Active API URL (e.g. https://mimic-clean-14323.nonamesec.com/active)"
    required: true
  ACTIVE_API_TOKEN:
    description: "Active API token (JWT) – pass via secret"
    required: true
  ACTIVE_BACKEND_URI:
    description: "Active backend URI"
    required: true
  TEST_GROUP_ID:
    description: "Test group ID"
    required: true
  ENVIRONMENT_NAME:
    description: "Environment / branch name"
    required: false
    default: "${{ github.ref_name }}"
  ACTIVE_CONFIG_FILE_PATH:
    description: "Path inside container to config file (mounted from ./akamai)"
    required: false
    default: "/akamai/environment.json"
  VERBOSE:
    description: "Enable verbose output"
    required: false
    default: "false"
  ANALYZE:
    description: "Enable analyze mode"
    required: false
    default: "false"
  SEVERITY_THRESHOLD:
    description: "Severity threshold (e.g. HIGH, MEDIUM)"
    required: false
    default: ""
  ISSUE_THRESHOLD:
    description: "Issue threshold (string)"
    required: false
    default: ""
  CATEGORY_THRESHOLD:
    description: "Category threshold (string)"
    required: false
    default: ""
  CONCURRENCY:
    description: "Concurrency level (number)"
    required: false
    default: ""
  TIMEOUT:
    description: "Timeout in seconds (number)"
    required: false
    default: ""
  PROXY:
    description: "HTTP proxy URL"
    required: false
    default: ""
  BACKEND_PROXY:
    description: "Backend HTTP proxy URL"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Log versions / debug
      shell: bash
      run: |
        echo "Running Active scan..."
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Branch / ref: $GITHUB_REF_NAME"

    - name: Docker login to Active registry
      shell: bash
      run: |
        set -euo pipefail
        docker login "${{ inputs.ACTIVE_REGISTRY_URL }}" \
          -u "${{ inputs.ACTIVE_REGISTRY_USER }}" \
          -p "${{ inputs.ACTIVE_REGISTRY_PASSWORD }}"

    - name: Run Active CLI scan
      shell: bash
      run: |
        set -eo pipefail

        # Fetch CLI image version from Active API
        VERSION=$(curl -ks "${{ inputs.ACTIVE_API_URL }}/backend/version")
        echo "Using active-cli image tag: $VERSION"

        docker run \
          --network=host \
          -e ACTIVE_CONFIG_FILE_PATH="${{ inputs.ACTIVE_CONFIG_FILE_PATH }}" \
          -e ACTIVE_BACKEND_URI="${{ inputs.ACTIVE_BACKEND_URI }}" \
          $(if [[ -n "${{ inputs.BACKEND_PROXY }}" ]]; then \
             if [[ "${{ inputs.BACKEND_PROXY }}" == http:* ]]; then \
               echo "-e ACTIVE_REMOTE_WORKER_HTTP_PROXY='${{ inputs.BACKEND_PROXY }}'"; \
             else \
               echo "-e ACTIVE_REMOTE_WORKER_HTTPS_PROXY='${{ inputs.BACKEND_PROXY }}'"; \
             fi; \
           fi) \
          -v "$GITHUB_WORKSPACE/akamai:/akamai" \
          "${{ inputs.ACTIVE_REGISTRY_URL }}/active-cli:${VERSION}" \
          scan \
          --api-url="${{ inputs.ACTIVE_API_URL }}" \
          --api-token="${{ inputs.ACTIVE_API_TOKEN }}" \
          --test-group-id="${{ inputs.TEST_GROUP_ID }}" \
          --branch-name="${{ inputs.ENVIRONMENT_NAME }}" \
          $([[ "${{ inputs.VERBOSE }}" == "true" ]] && echo "--verbose") \
          $([[ "${{ inputs.ANALYZE }}" == "true" ]] && echo "--analyze") \
          $([[ -n "${{ inputs.SEVERITY_THRESHOLD }}" ]] && echo "--severity-threshold='${{ inputs.SEVERITY_THRESHOLD }}'") \
          $([[ -n "${{ inputs.ISSUE_THRESHOLD }}" ]] && echo "--issue-threshold='${{ inputs.ISSUE_THRESHOLD }}'") \
          $([[ -n "${{ inputs.CATEGORY_THRESHOLD }}" ]] && echo "--category-threshold='${{ inputs.CATEGORY_THRESHOLD }}'") \
          $([[ -n "${{ inputs.CONCURRENCY }}" ]] && echo "--concurrency='${{ inputs.CONCURRENCY }}'") \
          $([[ -n "${{ inputs.TIMEOUT }}" ]] && echo "--timeout='${{ inputs.TIMEOUT }}'") \
          $([[ -n "${{ inputs.PROXY }}" ]] && echo "--proxy='${{ inputs.PROXY }}'")
